import "./globals.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const satoshiFont = localFont({
  src: "../public/fonts/Satoshi-Variable.ttf",
  variable: "--satoshi-font",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${satoshiFont.variable} font-sans`}>{children}</body>
    </html>
  );
}
